export const ALL_CUISINES_REQUEST = "ALL_CUISINES_REQUEST";
export const ALL_CUISINES_SUCCESS = "ALL_CUISINES_SUCCESS";
export const ALL_CUISINES_FAIL = "ALL_CUISINES_FAIL";

export const CUISINE_DETAILS_REQUEST = "CUISINE_DETAILS_REQUEST";
export const CUISINE_DETAILS_SUCCESS = "CUISINE_DETAILS_SUCCESS";
export const CUISINE_DETAILS_FAIL = "CUISINE_DETAILS_FAIL";

export const NEW_CUISINE_REQUEST = "NEW_CUISINE_REQUEST";
export const NEW_CUISINE_SUCCESS = "NEW_CUISINE_SUCCESS";
export const NEW_CUISINE_FAIL = "NEW_CUISINE_FAIL";

export const UPDATE_CUISINE_REQUEST = "UPDATE_CUISINE_REQUEST";
export const UPDATE_CUISINE_SUCCESS = "UPDATE_CUISINE_SUCCESS";
export const UPDATE_CUISINE_RESET = "UPDATE_CUISINE_RESET";
export const UPDATE_CUISINE_FAIL = "UPDATE_CUISINE_FAIL";

export const DELETE_CUISINE_REQUEST = "DELETE_CUISINE_REQUEST";
export const DELETE_CUISINE_SUCCESS = "DELETE_CUISINE_SUCCESS";
export const DELETE_CUISINE_RESET = "DELETE_CUISINE_RESET";
export const DELETE_CUISINE_FAIL = "DELETE_CUISINE_FAIL";